-- CreateEnum
CREATE TYPE "ItemStatus" AS ENUM ('OK', 'ERROR', 'NEW_ACCOUNTS_AVAILABLE', 'PENDING_DISCONNECT', 'PENDING_EXPIRATION', 'USER_PERMISSION_REVOKED');

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "status" "ItemStatus" NOT NULL DEFAULT 'OK';
